# Start configuration added by Zim install {{{
#
# User configuration sourced by all invocations of the shell
#

# Define Zim location
: ${ZIM_HOME=${XDG_CONFIG_HOME}/.zim}
# }}} End configuration added by Zim install

