#!/bin/env bash

#notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")
#$(date "+%Y/%b/%d ( %a ) %I:%M%p")
#"
#notify-send "This Month" "$(cal --color=always )"
setsid -f st -e gotop

