#! /bin/sh

### --- startup --- ###
#sleep 1 ; /bin/bash ~/.local/mbin/bspwm/bspwm-autostart.sh &
pgrep -f bspwm-autostart.sh || /bin/bash ~/.local/mbin/bspwm/bspwm-autostart.sh &

### --- config --- ###
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap           20


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#FEFDD3

### --- rule --- ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=fullscreen

